id: Util
namespace: OffByOneStudios
shortname: Craft Util
version: "1.0.0"
repo: http://github.com/OffByOneStudios/craft-util
dependencies: []

vendor-dependencies:
  x86_64-pc-windows-msvccoff: []
  osx_x64_clang: []
  x86_64-pc-linux-gnu: []

platform-dependencies:
  x86_64-pc-windows-msvccoff:
    - Ws2_32.lib
    - pathcch.lib
    - shlwapi.lib
    - Shell32.lib

  osx_x64_clang:
    - '"-framework Security"'
  x86_64-pc-linux-gnu: []

platform-flags:
  x86_64-pc-windows-msvccoff: []
  osx_x64_clang:
    - "-std=c++1z"
    - "-stdlib=libc++"
    - "-Wc++11-extensions"
  x86_64-pc-linux-gnu:
    - "-std=gnu++1z"
    - "-pthread"
    - "-fpermissive"

artifacts:
  library:
    primary: yes
    kind: dll
    files:
      - src/**/*.*
  test:
    kind: test
    files:
      - test/**/*.*
  entry:
    kind: exe
    files:
      - entry/**/*.*
