id: Util
namespace: OffByOneStudios
shortname: Craft Util
version: "1.0.0"
repo: http://github.com/OffByOneStudios/craft-util
dependencies: []

vendor-dependencies:
  x86_64-pc-windows-msvccoff:
    - libcurl
    - picohttpparser
  osx_x64_clang:
    - curl
    - picohttpparser
  debian_x64_gcc:
    - curl
    - picohttpparser

platform-dependencies:
  x86_64-pc-windows-msvccoff:
    - Ws2_32.lib
    - pathcch.lib
    - shlwapi.lib
    - Shell32.lib

  osx_x64_clang:
    - '"-framework Security"'
  debian_x64_gcc: []

platform-flags:
  x86_64-pc-windows-msvccoff: []
  osx_x64_clang:
    - "-std=c++1z"
    - "-stdlib=libc++"
    - "-Wc++11-extensions"
  debian_x64_gcc:
    - "-std=gnu++1z"
    - "-pthread"
    - "-fpermissive"


files:
  library:
    - src/**/*.*
  test:
    - test/**/*.*
  entry:
    - entry/**/*.*
